/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 25-Dec-2010, 3:20:45 PM
 */



import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.text.BadLocationException;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JTextPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextArea;

public class GUI extends javax.swing.JFrame {
	//Communicator object
	msgClass msgCla = null;
	//KeybindingController object
	KeybindingController keybindingController = null;
	Graphics pGraphics;
	JPanel panel = new JPanel();
	Point point;
	/** Creates new form GUI */
	public GUI() {
		initComponents();
		createObjects();
		point=new Point(5, 5);
		//communicator.searchForPorts();

	}



	private void createObjects()
	{
		msgCla = new msgClass(this);
		keybindingController = new KeybindingController(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		lblLeft = new javax.swing.JLabel();
		btnConnect = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Tiger Tank Control Panel");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel1.setText("Robot Communication Control Panel");

		lblLeft.setFont(new java.awt.Font("Tahoma", 1, 18));
		lblLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblLeft.setText("0");

		btnConnect.setText("Send");
		btnConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnConnectActionPerformed(evt);
				} catch (BadLocationException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel13.setText("Log");
		txtLog = new javax.swing.JTextArea();

		txtLog.setColumns(20);
		txtLog.setEditable(false);
		txtLog.setLineWrap(true);
		txtLog.setRows(5);
		txtLog.setFocusable(false);

		JLabel lblRobot = new JLabel();
		lblRobot.setText("Robot");
		lblRobot.setFont(new Font("Tahoma", Font.BOLD, 11));

		JButton btnLeft = new JButton("\u2190");
		btnLeft.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					msgCla.MoveLeft();
				} catch (BadLocationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});

		JButton btnRight = new JButton("\u2192");
		btnRight.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				try {
					msgCla.MoveRight();
				} catch (BadLocationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			
			}
		});

		JButton btnDown = new JButton("\u2193");
		btnDown.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					msgCla.MoveDown();
				} catch (BadLocationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}


			}
		});

		JButton btnUp = new JButton("\u2191");
		btnUp.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					msgCla.MoveUp();
				} catch (BadLocationException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});

		txtFrom = new JTextField();
		txtFrom.setColumns(10);



		JLabel lblNewLabel = new JLabel("msg");

		lblFrom = new JLabel("From");





		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addComponent(btnUp, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnLeft))
												.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(jLabel1)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(Alignment.LEADING)
																		.addComponent(lblFrom, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(lblLeft, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(Alignment.LEADING)
																						.addComponent(btnDown, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
																						.addComponent(btnRight))))
																						.addGroup(layout.createParallelGroup(Alignment.LEADING)
																								.addGroup(layout.createSequentialGroup()
																										.addGap(32)
																										.addComponent(txtMsg, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
																										.addGap(33)
																										.addComponent(btnConnect))
																										.addGroup(layout.createSequentialGroup()
																												.addGap(60)
																												.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)))))
																												.addGap(68))
																												.addGroup(layout.createSequentialGroup()
																														.addComponent(txtFrom, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
																														.addGap(311)))
																														.addPreferredGap(ComponentPlacement.RELATED)
																														.addComponent(txtPoint, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
																														.addGap(33)
																														.addGroup(layout.createParallelGroup(Alignment.LEADING)
																																.addGroup(layout.createSequentialGroup()
																																		.addComponent(panel, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
																																		.addGap(31)
																																		.addComponent(txtLog, GroupLayout.PREFERRED_SIZE, 227, GroupLayout.PREFERRED_SIZE))
																																		.addGroup(layout.createSequentialGroup()
																																				.addComponent(lblRobot, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
																																				.addGap(204)
																																				.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
																																				.addGap(342))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
						.addGap(11)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jLabel1)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(lblRobot))
										.addComponent(jLabel13))
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(Alignment.TRAILING)
																.addComponent(panel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
																.addComponent(txtLog, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
																.addContainerGap())
																.addGroup(layout.createSequentialGroup()
																		.addGroup(layout.createParallelGroup(Alignment.BASELINE)
																				.addComponent(lblFrom)
																				.addComponent(lblNewLabel))
																				.addGap(1)
																				.addGroup(layout.createParallelGroup(Alignment.LEADING)
																						.addComponent(txtPoint, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(txtFrom, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
																								.addGroup(layout.createParallelGroup(Alignment.LEADING)
																										.addGroup(layout.createSequentialGroup()
																												.addPreferredGap(ComponentPlacement.RELATED)
																												.addGroup(layout.createParallelGroup(Alignment.LEADING)
																														.addGroup(layout.createSequentialGroup()
																																.addComponent(btnUp)
																																.addPreferredGap(ComponentPlacement.RELATED)
																																.addGroup(layout.createParallelGroup(Alignment.BASELINE)
																																		.addComponent(btnLeft)
																																		.addComponent(btnRight)))
																																		.addComponent(btnDown)))
																																		.addGroup(layout.createSequentialGroup()
																																				.addGap(20)
																																				.addComponent(lblLeft))))
																																				.addComponent(txtMsg, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
																																				.addComponent(btnConnect, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
																																				.addGap(21))))
				);
		panel.setBackground(Color.WHITE);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) throws BadLocationException {//GEN-FIRST:event_btnConnectActionPerformed

		msgCla.sendMsg();


	}//GEN-LAST:event_btnConnectActionPerformed

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public JTextPane txtMsg = new JTextPane();
	public JTextArea txtPoint = new JTextArea();

	public javax.swing.JButton btnConnect;
	public javax.swing.JButton btnUp;
	public javax.swing.JButton btnDown;
	public javax.swing.JButton btnLeft;
	public javax.swing.JButton btnRight;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	public javax.swing.JLabel lblLeft;
	public javax.swing.JTextArea txtLog;
	public javax.swing.JTextArea txtRobot;
	JTextField txtFrom;
	private JLabel lblFrom;
}
